import { Agente, Cliente, Servicio, Producto, Insumo, BorradorEntry, SalonConfig } from "./types";
import { getTodayDateString } from "./utils";

export const INITIAL_CONFIG: SalonConfig = {
  nombre_salon: "Salón Élite & Spa",
  hora_cierre_auto: "22:00",
  zona_horaria: "America/Mexico_City",
  correlativo_actual: 104,
};

export const MOCK_AGENTES: Agente[] = [
  {
    id: "AG-001",
    nombre: "Valeria Morales",
    pin: "1234",
    rol: "admin",
    especialidades: ["estilista", "colorista"],
    telefono: "+52 55 1234 5678",
    email: "valeria.admin@salon.com",
    horario_lun: "09:00-19:00",
    horario_mar: "09:00-19:00",
    horario_mie: "09:00-19:00",
    horario_jue: "09:00-19:00",
    horario_vie: "09:00-20:00",
    horario_sab: "09:00-20:00",
    horario_dom: "",
    disponible_turnos: true,
    activo: true,
  },
  {
    id: "AG-002",
    nombre: "Carlos Mendoza",
    pin: "2345",
    rol: "agente",
    especialidades: ["estilista"],
    telefono: "+52 55 2345 6789",
    email: "carlos.m@salon.com",
    horario_lun: "10:00-18:00",
    horario_mar: "10:00-18:00",
    horario_mie: "10:00-18:00",
    horario_jue: "10:00-18:00",
    horario_vie: "10:00-19:00",
    horario_sab: "10:00-19:00",
    horario_dom: "",
    disponible_turnos: true,
    activo: true,
  },
  {
    id: "AG-003",
    nombre: "Sofía Navarro",
    pin: "3456",
    rol: "agente",
    especialidades: ["colorista", "tratamientos"],
    telefono: "+52 55 3456 7890",
    email: "sofia.color@salon.com",
    horario_lun: "09:00-17:00",
    horario_mar: "09:00-17:00",
    horario_mie: "09:00-17:00",
    horario_jue: "09:00-17:00",
    horario_vie: "09:00-18:00",
    horario_sab: "09:00-18:00",
    horario_dom: "",
    disponible_turnos: true,
    activo: true,
  },
  {
    id: "AG-004",
    nombre: "Mariana Ríos",
    pin: "4567",
    rol: "agente",
    especialidades: ["manicurista", "pedicurista"],
    telefono: "+52 55 4567 8901",
    email: "mariana.nails@salon.com",
    horario_lun: "10:00-19:00",
    horario_mar: "10:00-19:00",
    horario_mie: "10:00-19:00",
    horario_jue: "10:00-19:00",
    horario_vie: "10:00-20:00",
    horario_sab: "10:00-20:00",
    horario_dom: "",
    disponible_turnos: true,
    activo: true,
  },
  {
    id: "AG-005",
    nombre: "Alejandra Vega",
    pin: "5678",
    rol: "agente",
    especialidades: ["esteticista", "facial"],
    telefono: "+52 55 5678 9012",
    email: "alejandra.spa@salon.com",
    horario_lun: "11:00-19:00",
    horario_mar: "11:00-19:00",
    horario_mie: "11:00-19:00",
    horario_jue: "11:00-19:00",
    horario_vie: "11:00-20:00",
    horario_sab: "10:00-18:00",
    horario_dom: "",
    disponible_turnos: false,
    activo: true,
  },
];

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: "CL-001",
    nombre: "Camila Fernández",
    pin: "1111",
    telefono: "+52 55 9876 5432",
    email: "camila.f@gmail.com",
    agente_preferido: "AG-001",
    notas: "Prefiere café descafeinado. Alergia a tintes con amoníaco.",
    fecha_registro: "2025-01-15",
    activo: true,
  },
  {
    id: "CL-002",
    nombre: "Daniela Ortiz",
    pin: "2222",
    telefono: "+52 55 8765 4321",
    email: "daniela.o@outlook.com",
    agente_preferido: "AG-003",
    notas: "Tono rubio cenizo balayage recurrente.",
    fecha_registro: "2025-02-10",
    activo: true,
  },
  {
    id: "CL-003",
    nombre: "Lucía Castillo",
    pin: "3333",
    telefono: "+52 55 7654 3210",
    email: "lucia.castillo@gmail.com",
    agente_preferido: "AG-004",
    notas: "Esmalte semipermanente tono nude.",
    fecha_registro: "2025-03-05",
    activo: true,
  },
  {
    id: "CL-004",
    nombre: "Fernando Gómez",
    pin: "4444",
    telefono: "+52 55 6543 2109",
    email: "fgomez@corporativo.com",
    agente_preferido: "AG-002",
    notas: "Corte clásico fade bajo con perfilado de barba.",
    fecha_registro: "2025-04-12",
    activo: true,
  },
  {
    id: "CL-005",
    nombre: "Patricia Méndez",
    pin: "5555",
    telefono: "+52 55 5432 1098",
    email: "paty.mendez@hotmail.com",
    agente_preferido: "AG-005",
    notas: "Piel sensible mixta. Tratamiento hidratante.",
    fecha_registro: "2025-05-20",
    activo: true,
  },
];

export const MOCK_SERVICIOS: Servicio[] = [
  {
    id: "SV-001",
    nombre: "Corte y Peinado Dama",
    categoria: "cabello",
    especialidad_requerida: "estilista",
    duracion_min: 45,
    precio_base: 450,
    descripcion: "Lavado con shampoo reconstructor, corte según visagismo y secado profesional.",
    activo: true,
  },
  {
    id: "SV-002",
    nombre: "Corte Caballero & Perfilado",
    categoria: "cabello",
    especialidad_requerida: "estilista",
    duracion_min: 30,
    precio_base: 320,
    descripcion: "Degradado a máquina/tijera con acabado navaja y toalla tibia.",
    activo: true,
  },
  {
    id: "SV-003",
    nombre: "Balayage & Matización",
    categoria: "cabello",
    especialidad_requerida: "colorista",
    duracion_min: 150,
    precio_base: 1850,
    descripcion: "Decoloración progresiva a mano alzada, matiz tonalizante y tratamiento sellador.",
    activo: true,
  },
  {
    id: "SV-004",
    nombre: "Tinte Global Sin Amoníaco",
    categoria: "cabello",
    especialidad_requerida: "colorista",
    duracion_min: 90,
    precio_base: 890,
    descripcion: "Coloración orgánica de alta cobertura y brillo con nutrición botánica.",
    activo: true,
  },
  {
    id: "SV-005",
    nombre: "Manicura Rusa con Gel",
    categoria: "uñas",
    especialidad_requerida: "manicurista",
    duracion_min: 60,
    precio_base: 420,
    descripcion: "Limpieza profunda de cutícula con torno y esmaltado en gel de larga duración.",
    activo: true,
  },
  {
    id: "SV-006",
    nombre: "Pedicura Spa Hidratante",
    categoria: "uñas",
    especialidad_requerida: "pedicurista",
    duracion_min: 60,
    precio_base: 480,
    descripcion: "Exfoliación con sales minerales, mascarilla térmica y masaje relajante podal.",
    activo: true,
  },
  {
    id: "SV-007",
    nombre: "Limpieza Facial Profunda",
    categoria: "facial",
    especialidad_requerida: "facial",
    duracion_min: 75,
    precio_base: 750,
    descripcion: "Vapor de ozono, desincrustación ultrasónica, alta frecuencia y mascarilla calmante.",
    activo: true,
  },
  {
    id: "SV-008",
    nombre: "Tratamiento Botox Capilar",
    categoria: "cabello",
    especialidad_requerida: "tratamientos",
    duracion_min: 80,
    precio_base: 980,
    descripcion: "Relleno molecular de queratina y aminoácidos para eliminar frizz y aportar cuerpo.",
    activo: true,
  },
];

export const MOCK_PRODUCTOS: Producto[] = [
  {
    id: "PR-001",
    nombre: "Shampoo Nutritivo Argán 250ml",
    categoria: "cuidado_capilar",
    marca: "Moroccanoil",
    precio_venta: 580,
    stock: 18,
    activo: true,
  },
  {
    id: "PR-002",
    nombre: "Mascarilla Reparación Intensa 200ml",
    categoria: "tratamiento",
    marca: "Kérastase",
    precio_venta: 890,
    stock: 12,
    activo: true,
  },
  {
    id: "PR-003",
    nombre: "Aceite Serum Sellador de Puntas 100ml",
    categoria: "styling",
    marca: "Olaplex No. 7",
    precio_venta: 640,
    stock: 24,
    activo: true,
  },
  {
    id: "PR-004",
    nombre: "Aceite de Cutículas Vitamina E 15ml",
    categoria: "uñas",
    marca: "OPI ProSpa",
    precio_venta: 260,
    stock: 30,
    activo: true,
  },
  {
    id: "PR-005",
    nombre: "Serum Facial Ácido Hialurónico 30ml",
    categoria: "facial",
    marca: "Dermalogica",
    precio_venta: 950,
    stock: 8,
    activo: true,
  },
];

export const MOCK_INSUMOS: Insumo[] = [
  {
    id: "IN-001",
    nombre: "Crema Oxidante 20 Vol",
    categoria: "quimico",
    unidad_medida: "ml",
    stock: 4500,
    costo_unitario: 0.15,
    activo: true,
  },
  {
    id: "IN-002",
    nombre: "Polvo Decolorante Blonde Plus",
    categoria: "quimico",
    unidad_medida: "gr",
    stock: 2800,
    costo_unitario: 0.45,
    activo: true,
  },
  {
    id: "IN-003",
    nombre: "Guantes de Nitrilo Negro Talla M",
    categoria: "desechable",
    unidad_medida: "par",
    stock: 150,
    costo_unitario: 4.5,
    activo: true,
  },
  {
    id: "IN-004",
    nombre: "Papel de Mechas Térmico",
    categoria: "herramienta",
    unidad_medida: "hoja",
    stock: 600,
    costo_unitario: 1.2,
    activo: true,
  },
];

export const MOCK_BORRADOR: BorradorEntry[] = [
  {
    id_oatc: `OATC-${getTodayDateString().replace(/-/g, "")}-001`,
    fecha: getTodayDateString(),
    hora_inicio: "10:15",
    tipo_consumidor: "cliente",
    id_cliente: "CL-001",
    nombre_consumidor: "Camila Fernández",
    id_agente: "AG-001",
    nombre_agente: "Valeria Morales",
    id_servicio: "SV-001",
    nombre_servicio: "Corte y Peinado Dama",
    etapa: "atencion",
    precio_final: 450,
    productos_usados: "PR-003:1",
    insumos_usados: "IN-003:1",
    correlativo_sistema: "OATC-001",
    notas: "Cliente regular, corte de puntas 3cm.",
  },
  {
    id_oatc: `OATC-${getTodayDateString().replace(/-/g, "")}-002`,
    fecha: getTodayDateString(),
    hora_inicio: "11:00",
    tipo_consumidor: "turno",
    nombre_consumidor: "Laura Soria (Turno)",
    id_agente: "AG-004",
    nombre_agente: "Mariana Ríos",
    id_servicio: "SV-005",
    nombre_servicio: "Manicura Rusa con Gel",
    etapa: "asesoria",
    precio_final: 420,
    correlativo_sistema: "OATC-002",
    notas: "Turno asignado por cola de espera.",
  },
];
